---
  # Instalação
  - name: Instalar nginx
    apt:
      name: nginx
      state: present

  - name: Garantir que o nginx está parado
    become: yes
    service: name=nginx state=stopped enabled=yes
    ignore_errors: True

  - name: Criar diretórios de cache
    file:
      path: /tmp/assets-cache/tmp
      state: directory
      recurse: yes

  - name: Gerar certificado dhparam
    become: yes
    template: src=dhparam.pem dest=/etc/nginx/dhparam.pem

  # Configurações
  - name: Remover configuração padrão
    file: path=/etc/nginx/conf.d/default.conf state=absent

  - file: path=/etc/nginx/conf.d/example_ssl.conf state=absent

  - name: Configurar logrotate -> nginx
    template: src=logrotate dest=/etc/logrotate.d/nginx

  - name: Criar nginx.conf
    template: src=nginx.conf dest=/etc/nginx/nginx.conf

#  - name: Adicionar .htaccess
#    become: yes
#    template: src=supplai-{{ env_name }}.htpasswd dest=/etc/nginx/supplai-{{ env_name }}.htpasswd mode="0644" owner=root group=root

  - name: Criar fastcgi_params
    become: yes
    template: src=fastcgi_params dest=/etc/nginx/fastcgi_params mode="0644" owner=root group=root

#  - name: Criar vhost da Aplicação
#    become: yes
#    template: src=supplai-vhost.conf dest=/etc/nginx/conf.d/supplai.conf mode="0644" owner=root group=root

  - name: Criar proxy-cache.conf
    template: src=proxy-cache.conf dest=/etc/nginx/conf.d/proxy-cache.conf mode="0644" owner=root group=root

  - name: Iniciar nginx
    become: yes
    service: name=nginx state=restarted enabled=yes
