---
- name: Cria usuários para os membros da equipe
  hosts: "*"
  become: yes
  roles:
    - {"name": "permissions", "tags": "permissions"}

- name: Prepara ambiente para instalação das aplicações da {{ company_slug }}
  hosts: "*"
  become: yes
  roles:
    - {"name": "common", "tags": "common"}
    - {"name": "nginx", "tags": "nginx"}
    - {"name": "geerlingguy.postgresql", "tags": "postgresql"}

- name: Instala a Aplicação
  hosts: "*"
  tasks:
    - name: Enviando as configurações a aplicação para iniciar o deploy
      include_role:
        name: django_app
      vars:
        app_alias: "{{ project_app_alias }}"
        app_name: "{{ project_app_name }}"
        app_host: "{{ project_app_host }}"
        app_port: "{{ project_app_port }}"
        app_version: "{{ project_app_version }}"
        app_server_host: "{{ project_host }}"
        app_server_internal_host: "{{ project_internal_host }}"
        client_id: "{{ project_client_id }}"
        client_secret: "{{ project_client_secret }}"
        database_host: "{{ project_database_host }}"
        database_port: "{{ project_database_port }}"
        database_name: "{{ project_database_name }}"
        database_user: "{{ project_database_user }}"
        database_password: "{{ project_database_password }}"
        django_folder: "{{ project_django_folder }}"
        django_secret_key: "{{ project_django_secret_key }}"
        django_settings: "{{ project_django_settings }}"
        redis_database: "{{ project_redis_database }}"
        redis_host: "{{ project_redis_host }}"
        redis_port: "{{ project_redis_port }}"
        stats_port: "{{ project_stats_port }}"
        has_celery: "{{ project_has_celery }}"
        has_www_redirect: "{{ project_has_www_redirect }}"
  tags: [ 'django' ]
