---
- name: start nginx
  become: yes
  service: name=nginx state=started

- name: restart nginx
  become: yes
  service: name=nginx state=restarted

- name: stop nginx
  become: yes
  service: name=nginx state=stopped
