---
- apt_repository:
    repo: ppa:deadsnakes/ppa

- name: Atualiza o SO antes de instalar as dependencias
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Instalar dependencias comuns a todas as apps
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - git
      - build-essential
      - bzip2
      - openssl
      - xz-utils
      - libncurses5-dev
      - curl
      - libsqlite3-dev
      - libffi-dev
      - libssl-dev
      - libgdbm-dev
      - libnss3-dev
      - libreadline-dev
      - libbz2-dev
      - readline-common
      - zlib1g-dev
      - wget
      - python-dev
      - python3.8-dev
      - python3.8
      - python3-psycopg2
      - python-apt
      - redis-server
      - apache2-dev
    state: present
