---
- apt_repository:
    repo: ppa:deadsnakes/ppa

- name: Instalar dependencias comuns a todas as apps
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - git
      - build-essential
      - xz-utils
      - libncurses5-dev
      - curl
      - libsqlite3-dev
      - libffi-dev
      - libssl-dev
      - bzip2
      - mysql-client
      - readline-common
      - openssl
      - zlib1g-dev
      - supervisor
      - wget
      - libgdbm-dev
      - libnss3-dev
      - libreadline-dev
      - libbz2-dev
      - python3.8-dev
      - python3.8
      - python3-psycopg2
      - python-apt
      - redis-server
      - apache2-dev
      - binutils
      - libgeos-dev
      - gdal-bin
      - libgdal-dev
      - proj-bin
      - redis-server
    state: present




