---
galaxy_info:
  author: Rafael Henter
  description: Django Web App
  company: Henter S
  license: MIT
  min_ansible_version: 1.2
  platforms:
  - name: GenericUNIX
    versions:
    - all
    - any
  - name: GenericLinux
    versions:
    - all
    - any

  categories:
  - development
  - system
  - web
dependencies:
  []

