
---
  - name: Instalar certbot-nginx
    become: yes
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
        - certbot
        - python3-certbot-nginx

  - name: Registro no let's encrypt
    become: yes
    shell: "/usr/bin/certbot register -n -m {{ registration_email }} --no-eff-email --agree-tos"
    ignore_errors: True

  - name: Gerar certificado para {{ domain }}
    become: yes
    shell: "/usr/bin/certbot certonly -n --standalone --keep-until-expiring --agree-tos -d {{ domain }}"
    ignore_errors: True

  - name: Adicionar renovação do certificado ao crondaily
    become: yes
    template: src=roles/letsencrypt/templates/crondaily dest=/etc/cron.daily/letsencrypt mode="0755" owner=root group=root
    ignore_errors: True
