ansible_python_interpreter: /usr/bin/python3
python_version: 3.8.0

# timezone
ntp_enabled: true
ntp_timezone: America/Sao_Paulo

operation_team:
  - user_name

removed_users: []

# Company's name that will be used on all env
company_slug: company_name
